# Generated by Django 4.2.6 on 2023-10-12 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("genAPI", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Product",
        ),
    ]
