# Generated by Django 4.2.6 on 2023-10-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genAPI", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("price", models.IntegerField()),
                ("left", models.IntegerField()),
                ("description", models.CharField(max_length=200)),
                ("imagelink", models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
