# Generated by Django 4.2.6 on 2023-11-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genAPI', '0004_productinfo_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinfo',
            name='barcode',
            field=models.CharField(default='123123', max_length=200),
        ),
        migrations.AddField(
            model_name='productinfo',
            name='location',
            field=models.CharField(default='1A', max_length=20),
        ),
    ]
