# Generated by Django 4.2.6 on 2023-11-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genAPI', '0005_productinfo_barcode_productinfo_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='barcode',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productinfo',
            name='location',
            field=models.CharField(max_length=20),
        ),
    ]
