# Generated by Django 5.0.6 on 2024-08-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genAPI", "0006_alter_productinfo_barcode_alter_productinfo_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="productinfo",
            name="Category",
            field=models.CharField(default="Food", max_length=10),
        ),
        migrations.AddField(
            model_name="productinfo",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
