# Generated by Django 5.0.6 on 2024-08-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("genAPI", "0007_productinfo_category_productinfo_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinfo",
            name="Category",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Electronics", "Electronics"),
                    ("Clothing", "Clothing"),
                    ("Books", "Books"),
                    ("Toys", "Toys"),
                    ("Furniture", "Furniture"),
                    ("Household Goods", "Household Goods"),
                    ("Sports Equipment", "Sports Equipment"),
                    ("Beauty Products", "Beauty Products"),
                    ("Automotive", "Automotive"),
                ],
                default="Food",
                max_length=50,
            ),
        ),
    ]
